### 会话列表
GET {{contactHost}}/conversation
Authorization: 1

### 创建群会话
POST {{contactHost}}/conversation
Content-Type: application/json
Authorization: 1

{
  "type": "group",
  "object_id": 2
}

### 创建私聊会话
POST {{contactHost}}/conversation
Content-Type: application/json
Authorization:

{
  "type": "user",
  "object_id": 2
}

### 删除会话
DELETE {{contactHost}}/conversation/1
Authorization: 1

### 好友列表
GET {{contactHost}}/friend
Authorization: 1

### 好友信息修改;{id}:好友列表id
PUT {{contactHost}}fiend/1
Content-Type: application/json
Authorization: 1

{
  "remark": "好友备注"
}

### 删除好友;{id}:好友列表id
DELETE {{contactHost}}/friend/1
Authorization: 1

### 申请列表
GET {{contactHost}}/friend/apply
Authorization: 1

### 申请好友
POST {{contactHost}}/friend/apply
Content-Type: application/json
Authorization: 1

{
  "user_id": 2,
  "content": "申请理由"
}

### 申请同意;{id}:申请列表id
PUT {{contactHost}}/friend/apply/1
Authorization: 1

### 申请拒绝;{id}:申请列表id
DELETE {{contactHost}}/friend/apply/1
Authorization: 1

### 创建群
POST {{contactHost}}/group
Content-Type: application/json
Authorization: 1

{
  "name": "昵称",
  "avatar": "头像",
  "cover": "封面",
  "introduce": "简介"
}

### 我的群
GET {{contactHost}}/group/mine
Authorization: 1

### 群成员;{id}:群id
GET {{contactHost}}/group/1/member
Authorization: 1

### 加入群
POST {{contactHost}}/group/1/member
Authorization: 1

### 退出群
DELETE {{contactHost}}/group/1/member
Authorization: 1