### 私聊自定义
POST {{messageHost}}/message/private/publish
Content-Type: application/json
Authorization: 1

{
  "user_id": 2,
  "content_type": "TextMsg",
  "content": "",
  "url": "",
  "extra": "",
  "code": 6666
}

### 私聊文本
POST {{messageHost}}/message/private/publish/txt
Content-Type: application/json
Authorization: 2

{
  "user_id": 1,
  "content": "套你猴子",
  "extra": ""
}

### 私聊图片
POST {{messageHost}}/message/private/publish/img
Content-Type: application/json
Authorization: 2

{
  "user_id": 1,
  "content": "https://qvbilam.oss-cn-hangzhou.aliyuncs.com/user-images/noface.gif?x-oss-process=image/resize,m_fill,h_100,w_200",
  "url": "https://qvbilam.oss-cn-hangzhou.aliyuncs.com/user-images/noface.gif",
  "extra": ""
}

### 群聊自定义
POST {{messageHost}}/message/group/publish
Content-Type: application/json
Authorization: 1

{
  "group_id": 1,
  "content_type": "TextMsg",
  "content": "",
  "url": "",
  "extra": "",
  "code": 6666
}

### 群聊文本
POST {{messageHost}}/message/group/publish/txt
Content-Type: application/json
Authorization: 2

{
  "group_id": 1,
  "content": "hello",
  "url": "",
  "extra": ""
}

### 群聊图片
POST {{messageHost}}/message/group/publish/img
Content-Type: application/json
Authorization: 1

{
  "group_id": 1,
  "content": "缩略图",
  "url": "图片地址",
  "extra": ""
}

### 私聊聊天记录
GET {{messageHost}}/message/private/2?page=1&per_page=10
Authorization: 1

### 群聊聊天记录
GET {{messageHost}}/message/group/1?page=1&per_page=10
Authorization: 1