### 获取用户详情
GET {{userHost}}/user/1
Authorization: Bearer {{token}}

### 修改用户详情
PUT {{userHost}}/user
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "gender": "female"
}


### 搜索用户
GET {{userHost}}/user/search?keyword=fate
Authorization: Bearer {{token}}
