### 用户注册
POST {{userHost}}/account/register
Content-Type: application/json

{
  "mobile": "13501294112",
  "password": "123456"
}

### 用户登陆
POST {{userHost}}/account/login
Content-Type: application/json

{
  "mobile": "13501294164",
  "password": "123456",
  "method": "mobile"
}

> {% client.global.set("token", response.body.data.token) %}

### 获取用户详情
GET {{userHost}}/user/1
Authorization: Bearer {{token}}

### 修改用户详情
PUT {{userHost}}/user
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "gender": "female"
}


### 搜索用户
GET {{userHost}}/user/search?keyword=fate
Authorization: Bearer {{token}}
